[General]
# Custom_Clash_DEA 远程 YAML 模块
# 动态订阅选择由 /etc/openclash/custom/openclash_custom_overwrite.sh 完成。

DOWNLOAD_FILE = url=https://raw.githubusercontent.com/CDCEA/Custom_OpenClash_Rules/refs/heads/main/cfg/yaml/Custom_Clash_DEA.yaml, path=/etc/openclash/config/Custom_Clash_DEA.yaml, force=true
CONFIG_FILE = /etc/openclash/config/Custom_Clash_DEA.yaml
RESTART = true
